# Important Linear Algebra Skills for Physics Graduate Students:

# TODO: ADD functional navigation to document. Ex, skip to cell conatining section 1.5 heading

## 1. Matrix Operations

### 1.1 Addition and Subtraction

Matrix addition and sibtraction is performed element-wise. Only matrices of the same dimensions can be added or subtraced. 

$$
A = \begin{bmatrix}
a_1 & a_2 \\
a_3 & a_4
\end{bmatrix},
\quad
B = \begin{bmatrix}
b_1 & b_2 \\
b_3 & b_4
\end{bmatrix},
$$

The sum \( A + B \) is:
$$
A + B = \begin{bmatrix}
a_1+b_1 & a_2+b_2 \\
a_3+b_3 & a_4+b_4
\end{bmatrix}
$$

Given matrices \( C \) and \( D \):

Matrix \( C \):
$$
C = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Matrix \( D \):
$$
D = \begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}
$$

Both matrices are \( 2 x 3 \).

#### Matrix Addition
The sum \( C + D \) is:
$$
C + D = \begin{bmatrix}
1+7 & 2+8 & 3+9 \\
4+10 & 5+11 & 6+12
\end{bmatrix}
=
\begin{bmatrix}
8 & 10 & 12 \\
14 & 16 & 18
\end{bmatrix}
$$

#### Matrix Subtraction
The difference \( C - D \) is:
$$
C - D = \begin{bmatrix}
1-7 & 2-8 & 3-9 \\
4-10 & 5-11 & 6-12
\end{bmatrix}
=
\begin{bmatrix}
-6 & -6 & -6 \\
-6 & -6 & -6
\end{bmatrix}
$$

We can use a code cell to perform matrix addition and subtraction for us if we import the numpy library:

In [2]:
import numpy as np

# Define the matrices
C = np.array([[1, 2, 3],
              [4, 5, 6]])

D = np.array([[7, 8, 9],
              [10, 11, 12]])

# Perform matrix addition
E = C + D

# Perform matrix subtraction
F =  C - D

print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nMatrix C + D:")
print(E)

print("\nMatrix C - D:")
print(F)

Matrix C:
[[1 2 3]
 [4 5 6]]

Matrix D:
[[ 7  8  9]
 [10 11 12]]

Matrix C + D:
[[ 8 10 12]
 [14 16 18]]

Matrix C - D:
[[-6 -6 -6]
 [-6 -6 -6]]


### 1.2 Scalar Multiplication

Scalar matrix multiplication is performed by multiply every element in a matrix by a constant scalar. Given a matix A, and scalar c: 

$$
cA = c\begin{bmatrix}
a_1 & a_2 \\
a_3 & a_4
\end{bmatrix}
=
\begin{bmatrix}
ca_1 & ca_2 \\
ca_3 & ca_4
\end{bmatrix}
$$

Matrix \( A \):
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix},
$$
Scalar c:
$$
c = 2 
$$
Matrix \( B = cA\):
$$
B = cA = 2\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
= \begin{bmatrix}
2 & 4 & 6 \\
8 & 10 & 12
\end{bmatrix}
$$

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
c = 2
B = c * A

print("Matrix A:")
print(A)

print("\nMatrix B = cA:")
print(B)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B = cA:
[[ 2  4  6]
 [ 8 10 12]]


### 1.3 Matrix Multiplication

To multiply two matrices, ensure the number of columns in the first matrix matches the number of rows in the second. For each element in the resulting matrix, multiply corresponding elements from the row of the first matrix and the column of the second, then sum these products. Repeat this process for all elements in the resulting matrix.

Given matrices \( A \) and \( B \):

Matrix \( A \):
$$
A = \begin{bmatrix}
a_1 & a_2 & a_3 \\
a_4 & a_5 & a_6
\end{bmatrix}
$$

Matrix \( B \):
$$
B = \begin{bmatrix}
b_1 & b_2  \\
b_3 & b_4  \\
b_5 & b_6 
\end{bmatrix}
$$

Matix A has dimensions: 2 x 3, while Matrix B has dimension: 3 x 2. Multiplying matrix A and B will therefor result in a 2 x 2 matrix: 

Matrix \(C = AB \):
$$
C = AB = 
\begin{bmatrix}
a_1 & a_2 & a_3 \\
a_4 & a_5 & a_6
\end{bmatrix}
\begin{bmatrix}
b_1 & b_2  \\
b_3 & b_4  \\
b_5 & b_6 
\end{bmatrix}
= 
\begin{bmatrix}
a_1b_1+ a_2b_3 + a_3b_5 & a_1b_2+ a_2b_4 + a_3b_6\\
a_4b_1+ a_5b_3 + a_6b_5 & a_4b_2+ a_5b_4 + a_6b_6  
\end{bmatrix}
$$

Introducing index notation, the element in row i and column j of a the product matrix C is equal to the dot-product of row i of matrix A and column j of matrix B: 

$$
C_{ij} = (AB)_{ij} = \sum_k A_{ik}B_{kj}
$$
Commutation Example; Given matrices \( A \) and \( B \): 

$$
A = \begin{bmatrix}
3 & -1  \\
-4 & 2 
\end{bmatrix}, 
B = \begin{bmatrix}
5 & 2  \\
-7 & 3  
\end{bmatrix}
$$

$$
AB = \begin{bmatrix}
3 & -1  \\
-4 & 2 
\end{bmatrix}
\begin{bmatrix}
5 & 2  \\
-7 & 3  
\end{bmatrix}
=
\begin{bmatrix}
15 + 7 & 6 - 3  \\
-20 - 14 & -8 + 6  
\end{bmatrix}
=
\begin{bmatrix}
22 & 3  \\
-34 & -2  
\end{bmatrix}
$$

$$
BA = \begin{bmatrix}
5 & 2  \\
-7 & 3  
\end{bmatrix}
\begin{bmatrix}
3 & -1  \\
-4 & 2 
\end{bmatrix}
=
\begin{bmatrix}
15 + -8 & -5 + 4  \\
-21 - 12 & 7 + 6   
\end{bmatrix}
=
\begin{bmatrix}
7 & -1  \\
-33 & 13   
\end{bmatrix}
$$

Notice that the order that matrices are multiplied in matters. AB is not equal to BA, matrix mulitplication is in gernal not commutative (although there are matrices that commute). The commutator of two matrices A and B is defined as: 

$$
[A, B] = AB - BA
$$

This operator comes up very often in quantum mechanics. Two matrices commute if their commutator is equal to zero. 

In [6]:
import numpy as np

def doesCommute(M_1, M_2):
    
    # Perform matrix multiplication
    # Note: matrices are not multiplied by using M_1 * M_2 in python
    M_3 = np.dot(M_1, M_2)
    M_4 = np.dot(M_2, M_1)
    
    print("M_1 * M_2")
    print(M_3)
    
    print("\nM_2 * M_1")
    print(M_4)
    
    # Check if resulting matrices are equal using np.array_equal(M_3, M_4)
    if np.array_equal(M_3, M_4): 
        print("\nMatrices commute")
    else:
        print("\nMatrices do not cummute")
        
A = np.array([[3, -1],
              [-4, 2]])

B = np.array([[5, 2],
              [-7, 3]])

C = np.array([[1, 0],
              [0, 2]])

D = np.array([[3, 0],
              [0, 3]])

print("------------------------")
doesCommute(A,B)
print("------------------------")
doesCommute(C,D)
print("------------------------")

------------------------
M_1 * M_2
[[ 22   3]
 [-34  -2]]

M_2 * M_1
[[  7  -1]
 [-33  13]]

Matrices do not cummute
------------------------
M_1 * M_2
[[3 0]
 [0 6]]

M_2 * M_1
[[3 0]
 [0 6]]

Matrices commute
------------------------


### 1.4 Transpose of a Matrix 

To take the transpose of a matrix, intercahnge the rows and columns of the matrix. The dimensions of a m by n matrix will change to n by m under transpose. 
Given matrix \( A \):

Matrix \( A \):
$$
A = \begin{bmatrix}
a_1 & a_2 & a_3 \\
a_4 & a_5 & a_6
\end{bmatrix}
$$
Matrix \( Transopose of A \):
$$
A^T = \begin{bmatrix}
a_1 & a_4  \\
a_2 & a_5  \\
a_3 & a_6
\end{bmatrix}
$$

In index notation: 
$$
(A^T)_{ij} = A_{ji}
$$
Taking the transpose twice will give you back the original matrix: 
$$
(A^T)^T = A
$$

Example: 
$$
A = \begin{bmatrix}
1 & 5 & -2 \\
-3 & 0 & 6
\end{bmatrix}
$$

$$
A^T = \begin{bmatrix}
1 & -3  \\
5 & 0  \\
-2 & 6
\end{bmatrix}
$$

In [12]:
import numpy as np

A = np.array([[1, 5, -2],
              [-3, 0, 6]])

A_T = A.transpose()
A_T_T = A_T.transpose()

print("Matrix A")
print(A)

print("\nTranspose of A")
print(A_T)

print("\nTaking transpose again gives back original matrix A")
print(A_T_T)

Matrix A
[[ 1  5 -2]
 [-3  0  6]]

Transpose of A
[[ 1 -3]
 [ 5  0]
 [-2  6]]

Taking transpose again gives back original matrix A
[[ 1  5 -2]
 [-3  0  6]]


### 1.5 Inverse of a Matrix

## 2. Matrix Properties
### 2.1 Unitary Matrices
#### 2.1.1 Definition
#### 2.1.2 Properties
#### 2.1.3 Examples
### 2.2 Hermitian Matrices
#### 2.2.1 Definition
#### 2.2.2 Properties
#### 2.2.3 Examples
### 2.3 Orthogonal Matrices
#### 2.3.1 Definition
#### 2.3.2 Properties
#### 2.3.3 Examples
### 2.4 Positive Definite Matrices
#### 2.4.1 Definition
#### 2.4.2 Properties
#### 2.4.3 Examples

## 3. Determinants
### 3.1 Definition
### 3.2 Properties of Determinants
### 3.3 Computation Methods
#### 3.3.1 Laplace Expansion
#### 3.3.2 Row Reduction
### 3.4 Applications of Determinants
#### 3.4.1 Solving Linear Systems
#### 3.4.2 Cramer's Rule
#### 3.4.3 Area and Volume Calculation

## 4. Eigenvalues and Eigenvectors
### 4.1 Definitions
### 4.2 Properties
### 4.3 Computation Methods
#### 4.3.1 Characteristic Polynomial
#### 4.3.2 Diagonalization
### 4.4 Applications
#### 4.4.1 Stability Analysis
#### 4.4.2 Principal Component Analysis (PCA)
#### 4.4.3 Quantum Mechanics

## 5. Application to a Quantum Mechanics Problem
### 5.1 Introduction to Quantum Mechanics
### 5.2 The Schrödinger Equation
### 5.3 Using Linear Algebra in Quantum Mechanics
#### 5.3.1 Hamiltonian Matrix
#### 5.3.2 Finding Energy Levels (Eigenvalues)
#### 5.3.3 Wavefunctions (Eigenvectors)
### 5.4 Example Problem
#### 5.4.1 Problem Statement
#### 5.4.2 Solution Steps
#### 5.4.3 Interpretation of Results