# Important Linear Algebra Skills for Physics Graduate Students:

# TODO: ADD functional navigation to document. Ex, skip to cell conatining section 1.5 heading

## 1. Matrix Operations

### 1.1 Addition and Subtraction

Matrix addition and sibtraction is performed element-wise. Only matrices of the same dimensions can be added or subtraced. 

$$
A = \begin{bmatrix}
a_1 & a_2 \\
a_3 & a_4
\end{bmatrix},
\quad
B = \begin{bmatrix}
b_1 & b_2 \\
b_3 & b_4
\end{bmatrix},
$$

The sum \( A + B \) is:
$$
A + B = \begin{bmatrix}
a_1+b_1 & a_2+b_2 \\
a_3+b_3 & a_4+b_4
\end{bmatrix}
$$

Given matrices \( C \) and \( D \):

Matrix \( C \):
$$
C = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

Matrix \( D \):
$$
D = \begin{bmatrix}
7 & 8 & 9 \\
10 & 11 & 12
\end{bmatrix}
$$

Both matrices are \( 2 x 3 \).

#### Matrix Addition
The sum \( C + D \) is:
$$
C + D = \begin{bmatrix}
1+7 & 2+8 & 3+9 \\
4+10 & 5+11 & 6+12
\end{bmatrix}
=
\begin{bmatrix}
8 & 10 & 12 \\
14 & 16 & 18
\end{bmatrix}
$$

#### Matrix Subtraction
The difference \( C - D \) is:
$$
C - D = \begin{bmatrix}
1-7 & 2-8 & 3-9 \\
4-10 & 5-11 & 6-12
\end{bmatrix}
=
\begin{bmatrix}
-6 & -6 & -6 \\
-6 & -6 & -6
\end{bmatrix}
$$

We can use a code cell to perform matrix addition and subtraction for us if we import the numpy library:

In [16]:
import numpy as np

# Define the matrices
C = np.array([[1, 2, 3],
              [4, 5, 6]])

D = np.array([[7, 8, 9],
              [10, 11, 12]])

# Perform matrix addition
E = C + D

# Perform matrix subtraction
F =  C - D

print("Matrix C:")
print(C)

print("\nMatrix D:")
print(D)

print("\nMatrix C + D:")
print(E)

print("\nMatrix C - D:")
print(F)

Matrix C:
[[1 2 3]
 [4 5 6]]

Matrix D:
[[ 7  8  9]
 [10 11 12]]

Matrix C + D:
[[ 8 10 12]
 [14 16 18]]

Matrix C - D:
[[-6 -6 -6]
 [-6 -6 -6]]


### 1.2 Scalar Multiplication

Scalar matrix multiplication is performed by multiply every element in a matrix by a constant scalar. Given a matix A, and scalar c: 

$$
cA = c\begin{bmatrix}
a_1 & a_2 \\
a_3 & a_4
\end{bmatrix}
=
\begin{bmatrix}
ca_1 & ca_2 \\
ca_3 & ca_4
\end{bmatrix}
$$

Matrix \( A \):
$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix},
$$
Scalar c:
$$
c = 2 
$$
Matrix \( B = cA\):
$$
B = cA = 2\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
= \begin{bmatrix}
2 & 4 & 6 \\
8 & 10 & 12
\end{bmatrix}
$$

In [14]:
import numpy 

A = np.array([[1, 2, 3],
              [4, 5, 6]])
c = 2
B = c * A

print("Matrix A:")
print(A)

print("\nMatrix B = cA:")
print(B)

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B = cA:
[[ 2  4  6]
 [ 8 10 12]]


### 1.3 Matrix Multiplication



### 1.4 Transpose of a Matrix

### 1.5 Inverse of a Matrix

## 2. Matrix Properties
### 2.1 Unitary Matrices
#### 2.1.1 Definition
#### 2.1.2 Properties
#### 2.1.3 Examples
### 2.2 Hermitian Matrices
#### 2.2.1 Definition
#### 2.2.2 Properties
#### 2.2.3 Examples
### 2.3 Orthogonal Matrices
#### 2.3.1 Definition
#### 2.3.2 Properties
#### 2.3.3 Examples
### 2.4 Positive Definite Matrices
#### 2.4.1 Definition
#### 2.4.2 Properties
#### 2.4.3 Examples

## 3. Determinants
### 3.1 Definition
### 3.2 Properties of Determinants
### 3.3 Computation Methods
#### 3.3.1 Laplace Expansion
#### 3.3.2 Row Reduction
### 3.4 Applications of Determinants
#### 3.4.1 Solving Linear Systems
#### 3.4.2 Cramer's Rule
#### 3.4.3 Area and Volume Calculation

## 4. Eigenvalues and Eigenvectors
### 4.1 Definitions
### 4.2 Properties
### 4.3 Computation Methods
#### 4.3.1 Characteristic Polynomial
#### 4.3.2 Diagonalization
### 4.4 Applications
#### 4.4.1 Stability Analysis
#### 4.4.2 Principal Component Analysis (PCA)
#### 4.4.3 Quantum Mechanics

## 5. Application to a Quantum Mechanics Problem
### 5.1 Introduction to Quantum Mechanics
### 5.2 The Schrödinger Equation
### 5.3 Using Linear Algebra in Quantum Mechanics
#### 5.3.1 Hamiltonian Matrix
#### 5.3.2 Finding Energy Levels (Eigenvalues)
#### 5.3.3 Wavefunctions (Eigenvectors)
### 5.4 Example Problem
#### 5.4.1 Problem Statement
#### 5.4.2 Solution Steps
#### 5.4.3 Interpretation of Results